# Generated by Django 5.2.3 on 2025-06-22 22:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('passport_series', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Номер паспорта')),
                ('issued_by', models.TextField(verbose_name='Кем выдан')),
                ('registration', models.TextField(verbose_name='Адрес регистрации')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DKPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_file', models.FileField(upload_to='templates/')),
                ('doc_type', models.CharField(choices=[('LAND', 'Земельный участок'), ('APARTMENT', 'Квартира'), ('HOUSE', 'Дом с участком')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('LAND', 'Земельный участок'), ('APARTMENT', 'Квартира'), ('HOUSE', 'Дом с участком')], max_length=20)),
                ('cadastral_number', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('passport_series', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Номер паспорта')),
                ('issued_by', models.TextField(verbose_name='Кем выдан')),
                ('registration', models.TextField(verbose_name='Адрес регистрации')),
                ('is_individual', models.BooleanField(default=True, verbose_name='Физ. лицо')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedDKP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_in_words', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to='generated_docs/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.buyer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.dkptemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.realestate')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.seller')),
            ],
        ),
    ]
