# Generated by Django 5.2.3 on 2025-06-29 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_individual',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[А-Яа-яЁё\\s-]+$')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='cadastral_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^\\d{2}:\\d{2}:\\d{6,7}:\\d+$')]),
        ),
        migrations.AlterField(
            model_name='seller',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[А-Яа-яЁё\\s-]+$')], verbose_name='ФИО'),
        ),
    ]
